export const routePath = {
  ABOUT: '/about',
  ADD_FEEDBACK: '/add_feedback',
  AGREMEENT: '/agreement',
  AUTH: '/auth/login',
  CATEGORIES: '/categories',
  COMMUNNITY_RULES: 'сommunity_rules',
  FEEDBACK: '/feedback/:id',
  HOME: '/',
  LOGOUT: '/auth/logout',
  ME: '/auth/me',
  NOT_FOUND: '/404',
  PROFILE: '/profile',
  REFRESH_TOKEN: '/auth/refresh-tokens',
  REGISTRATION: '/auth/register',
  RESET_PASSWORD: '/auth/forgot-password',
  SEND_VERIFY_EMAIL: '/auth/send-verification-email',
  VERIFY_EMAIL: '/auth/verify-email',
} as const;
