export const routePath = {
  HOME: "/",
  AUTH: "/auth/login",
  ME: "/auth/me",
  REGISTRATION: "/auth/register",
  CATEGORIES: "/categories",
  LOGOUT: "/auth/logout",
  REFRESH_TOKEN: "/auth/refresh-tokens",
  RESET_PASSWORD: "/auth/forgot-password",
  SEND_VERIFY_EMAIL: "/auth/send-verification-email",
  VERIFY_EMAIL: "/auth/verify-email",
  ADD_FEEDBACK: "/add_feedback",
  PROFILE: "/profile",
  FEEDBACK_PAGE: "/feedbacks/:id",
  FEEDBACK_RATE: "/feedbacks/rate/",
  FEEDBACK: "/feedbacks/",
  AGREMEENT: "/agreement",
  COMMUNNITY_RULES: "сommunity_rules",
  ABOUT: "/about",
  NOT_FOUND: "/404",
} as const;
