name: Frontend checker, will punish for bad code 🪓😵‍💫
run-name: ${{ github.actor }} is starting sueta at the frontend code ☺️

on:
  push:
    branches:
      - main
      - dev
    paths:
      - "client/**"
  pull_request:
    branches:
      - main
      - dev
    paths:
      - "client/**"

jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.JS ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}

      - name: Install npm and dependencies
        working-directory: ./client
        run: npm install

      - name: Build project
        working-directory: ./client
        run: npm run build

  deploy:
    needs: pipeline
    if: success()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check if on main branch
        id: check_branch
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "::set-output name=is_main::true"
          else
            echo "::set-output name=is_main::false"
          fi

      - name: Set Vercel Args
        id: vercel_args
        run: |
          if [[ "${{ steps.check_branch.outputs.is_main }}" == "true" && "${{ github.event_name }}" == "push" ]]; then
            echo "::set-output name=args::--prod"
          else
            echo "::set-output name=args::"
          fi

      - name: Deploy Frontend
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          vercel-args: ${{ steps.vercel_args.outputs.args }}